"""
coursecraft init.

Creates ./course/ -- a fresh git repo that `update` will regenerate
content into on every run, never hand-edited -- and, if one doesn't
already exist, a placeholder ./course.yaml alongside it with a real
notes_repo but every other required field set to REPLACE_ME, so
`coursecraft validate` fails loudly until they're actually filled in.

init and fetch-notes are deliberately separate commands (see
ARCHITECTURE.md): init is purely local and can't fail for reasons
outside your control; fetch-notes depends on the network and produces
a real external side effect (a pushed branch). Composing them is
`build`'s job, not something either command should do on its own.
"""

import os
import subprocess
from pathlib import Path
from typing import Optional

import yaml

PLACEHOLDER = "REPLACE_ME"

# Rejects any commit into course/ unless coursecraft itself set this
# env var first -- course/ is regenerated wholesale by `update` on
# every run, so a hand-made commit here would just be silently
# overwritten (or worse, conflict with) the next run anyway. Checked
# from the very first commit onward: installed here in init, not
# deferred to update's first run, so there's no gap where a stray
# manual commit could slip through uncaught.
PRE_COMMIT_HOOK = """#!/bin/sh
if [ "$COURSECRAFT_INTERNAL" != "1" ]; then
    echo "Direct commits to this repo are not allowed." >&2
    exit 1
fi
exit 0
"""

GITIGNORE = """.quarto/
_book/
_site/
*_files/
.DS_Store
"""

README = """# course

Generated by `coursecraft update`. Edit notes/, not this directory --
anything changed here is overwritten on the next update.
"""


class InitError(Exception):
    pass


def _run(cmd: list[str], env: Optional[dict] = None) -> subprocess.CompletedProcess:
    result = subprocess.run(cmd, capture_output=True, text=True, env=env)
    if result.returncode != 0:
        raise InitError(f"command failed: {' '.join(cmd)}\n{result.stderr.strip()}")
    return result


def _scaffold_course_yaml(
    path: Path, notes_repo: str, notes_branch: Optional[str]
) -> bool:
    """Write a placeholder course.yaml if one doesn't already exist.
    Returns True if a file was written, False if one already existed
    (left completely untouched either way -- never overwritten)."""
    if path.exists():
        return False

    course: dict = {"title": PLACEHOLDER, "notes_repo": notes_repo}
    if notes_branch:
        course["notes_branch"] = notes_branch

    data = {
        "course": course,
        "section": {
            "instructor": PLACEHOLDER,
            "course_number": PLACEHOLDER,
            "term": PLACEHOLDER,
            "location": PLACEHOLDER,
            "meeting_times": PLACEHOLDER,
            "start_date": PLACEHOLDER,
            "end_date": PLACEHOLDER,
        },
        "lectures": [],
        "assignments": [],
    }
    header = (
        "# Generated by `coursecraft init`. Fields set to REPLACE_ME "
        "require a real value.\n"
    )
    path.write_text(header + yaml.dump(data, sort_keys=False))
    return True


def init(
    notes_repo: str,
    notes_branch: Optional[str] = None,
    course_dir: str = "course",
    course_yaml_path: str = "course.yaml",
) -> tuple[Path, bool]:
    """Create course_dir (a fresh, protected git repo) and, if
    missing, a placeholder course.yaml alongside it. Raises InitError
    if course_dir already exists -- checked first, before
    course_yaml_path is touched at all, so a failed init never leaves
    a stray scaffolded file as a side effect."""
    course_path = Path(course_dir)
    if course_path.exists():
        raise InitError(f"'{course_path}' already exists.")

    course_path.mkdir()
    internal_env = {
        **os.environ,
        "COURSECRAFT_INTERNAL": "1",
        # coursecraft's own commits shouldn't depend on the host having
        # git identity configured at all (a fresh CI runner won't) --
        # and giving them a consistent, distinct identity also makes
        # machine-generated history clearly attributable, rather than
        # showing up under whatever human happens to be running this.
        "GIT_AUTHOR_NAME": "coursecraft",
        "GIT_AUTHOR_EMAIL": "coursecraft@localhost",
        "GIT_COMMITTER_NAME": "coursecraft",
        "GIT_COMMITTER_EMAIL": "coursecraft@localhost",
    }

    _run(["git", "init", "-b", "main", str(course_path)])

    hook_path = course_path / ".git" / "hooks" / "pre-commit"
    hook_path.write_text(PRE_COMMIT_HOOK)
    hook_path.chmod(0o755)

    (course_path / ".gitignore").write_text(GITIGNORE)
    (course_path / "README.md").write_text(README)

    _run(["git", "-C", str(course_path), "add", "-A"], env=internal_env)
    _run(
        ["git", "-C", str(course_path), "commit", "-m", "Initial commit"],
        env=internal_env,
    )

    wrote_yaml = _scaffold_course_yaml(
        Path(course_yaml_path), notes_repo, notes_branch
    )

    return course_path, wrote_yaml
