"""
coursecraft init.

Creates ./course/ -- a fresh git repo that `update` will regenerate
content into on every run, never hand-edited -- and, if one doesn't
already exist, a placeholder ./course.yml alongside it with a real
notes_repo but every other required field set to REPLACE_ME, so
`coursecraft validate` fails loudly until they're actually filled in.

init and fetch-notes are deliberately separate commands (see
ARCHITECTURE.md): init is purely local and can't fail for reasons
outside your control; fetch-notes depends on the network and produces
a real external side effect (a pushed branch). Composing them is
`build`'s job, not something either command should do on its own.
"""

from pathlib import Path
from typing import Optional

import yaml

from ._gitutil import run_git, GitCommandError, coursecraft_env

PLACEHOLDER = "REPLACE_ME"

# Rejects any commit into course/ unless coursecraft itself set this
# env var first -- course/ is regenerated wholesale by `update` on
# every run, so a hand-made commit here would just be silently
# overwritten (or worse, conflict with) the next run anyway. Checked
# from the very first commit onward: installed here in init, not
# deferred to update's first run, so there's no gap where a stray
# manual commit could slip through uncaught.
PRE_COMMIT_HOOK = """#!/bin/sh
if [ "$COURSECRAFT_INTERNAL" != "1" ]; then
    echo "Direct commits to this repo are not allowed." >&2
    exit 1
fi
exit 0
"""

GITIGNORE = """.quarto/
_book/
_site/
*_files/
.DS_Store
"""

README = """# course

Generated by `coursecraft update`. Edit notes/, not this directory --
anything changed here is overwritten on the next update.
"""

INDEX_QMD = """# Syllabus {.unnumbered}

*Syllabus not yet generated. Run `coursecraft update` to populate this page.*
"""


class InitError(Exception):
    pass


def _run(cmd: list[str], env: Optional[dict] = None):
    try:
        return run_git(cmd, env=env)
    except GitCommandError as e:
        raise InitError(str(e)) from e


def _scaffold_course_yaml(
    path: Path, notes_repo: str, notes_branch: Optional[str]
) -> bool:
    """Write a placeholder course.yml if one doesn't already exist.
    Returns True if a file was written, False if one already existed
    (left completely untouched either way -- never overwritten)."""
    if path.exists():
        return False

    course: dict = {"title": PLACEHOLDER, "notes_repo": notes_repo}
    if notes_branch:
        course["notes_branch"] = notes_branch

    data = {
        "course": course,
        "section": {
            "instructor": PLACEHOLDER,
            "course_number": PLACEHOLDER,
            "term": PLACEHOLDER,
            "location": PLACEHOLDER,
            "meeting_times": PLACEHOLDER,
            "start_date": PLACEHOLDER,
            "end_date": PLACEHOLDER,
        },
        "lectures": [],
        "assignments": [],
    }
    header = (
        "# Generated by `coursecraft init`. Fields set to REPLACE_ME "
        "require a real value.\n"
    )
    path.write_text(header + yaml.dump(data, sort_keys=False), encoding="utf-8")
    return True


def init(
    notes_repo: str,
    notes_branch: Optional[str] = None,
    course_dir: str = "course",
    course_yaml_path: str = "course.yml",
) -> tuple[Path, bool]:
    """Create course_dir (a fresh, protected git repo) and, if
    missing, a placeholder course.yml alongside it. Raises InitError
    if course_dir already exists -- checked first, before
    course_yaml_path is touched at all, so a failed init never leaves
    a stray scaffolded file as a side effect."""
    course_path = Path(course_dir)
    if course_path.exists():
        raise InitError(f"'{course_path}' already exists.")

    course_path.mkdir()
    internal_env = coursecraft_env()

    _run(["git", "init", "-b", "main", str(course_path)])

    hook_path = course_path / ".git" / "hooks" / "pre-commit"
    hook_path.write_text(PRE_COMMIT_HOOK, encoding="utf-8")
    hook_path.chmod(0o755)

    (course_path / ".gitignore").write_text(GITIGNORE, encoding="utf-8")
    (course_path / "README.md").write_text(README, encoding="utf-8")
    (course_path / "index.qmd").write_text(INDEX_QMD, encoding="utf-8")

    _run(["git", "-C", str(course_path), "add", "-A"], env=internal_env)
    _run(
        ["git", "-C", str(course_path), "commit", "-m", "Initial commit"],
        env=internal_env,
    )

    wrote_yaml = _scaffold_course_yaml(
        Path(course_yaml_path), notes_repo, notes_branch
    )

    return course_path, wrote_yaml
